### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by mischugo** [kenmoore/sketch-better-paste#5]
This plug in crashes my sketch file. also when, i try a other short cut for this event. :-(((

**Comment by kenmoore** [comment]
Thanks for the report, and sorry for the crash.  Are you using Sketch 3.3?  Also, how many artboards do you have in your document?  Are you pasting an object from Sketch itself or pasting something copied outside of Sketch?  Does it happen every time you paste anything?  (try a document with 1 artboard and a simple rectangle -- copy and paste the rectangle into the same artboard).  The more detail you can provide of repro steps the better I'll be able to troubleshoot.  Thanks

**Comment by kenmoore** [comment]
Ping... are you still encountering the issue?

**Comment by mischugo** [comment]
i am so sorry.
Was sick and didn’t work.

I will come back soon!

Again, sorry!!!

Mit freundlichen Grüßen, Maik

**Comment by kenmoore** [comment]
Note that one of my coworkers had the crashing issue this morning, but it turns out she had an older version of the plugin.  We replaced it with the latest code and all worked fine, so maybe that'll work for you too, but let me know if not.

Hope you feel better soon.

**Comment by mischugo** [comment]
So, it works on my MacBookPro 2014, but not on my iMac 5K in the company :-(

Best, Maik

-- 
Maik Laufender

Absender: Ken Moore notifications@github.com
Antworten: kenmoore/sketch-better-paste reply@reply.github.com>
Datum: 8. Juni 2015 at 18:34:41
Empfänger: kenmoore/sketch-better-paste sketch-better-paste@noreply.github.com>
CC: mischugo maiklaufender@gmail.com>
Betreff:  Re: [sketch-better-paste] Crashes (#5)  

Note that one of my coworkers had the crashing issue this morning, but it turns out she had an older version of the plugin. We replaced it with the latest code and all worked fine, so maybe that'll work for you too, but let me know if not.

Hope you feel better soon.

**Comment by kenmoore** [comment]
Hm, are you certain you have the exact plugin script file on both
computers?  (an update in April fixed the main crashing bug)

**Comment by mischugo** [comment]
From tomorrow, i will no longer work in this company.
So, it works fin on my MacBookPro. That really ok for me :-)))

Best,
Maik

-- 
Maik Laufender

Absender: Ken Moore notifications@github.com
Antworten: kenmoore/sketch-better-paste reply@reply.github.com>
Datum: 11. Juni 2015 at 16:46:59
Empfänger: kenmoore/sketch-better-paste sketch-better-paste@noreply.github.com>
CC: mischugo maiklaufender@gmail.com>
Betreff:  Re: [sketch-better-paste] Crashes (#5)  

Hm, are you certain you have the exact plugin script file on both
computers? (an update in April fixed the main crashing bug)

**Comment by kenmoore** [comment]
Fair enough, good luck with whatever's next!
