### ISSUE TITLE
Plugin directory listing

### ISSUE THREAD

**Issue by ricburton** [kenmoore/sketch-better-paste#6]
It’d be great if this was added to the Sketch Plugin Directory so it’s discoverable in Toolbox.

https://github.com/sketchplugins/plugin-directory

**Comment by bomberstudios** [comment]
It would be even better if you filed the issue in the plugin-directory repo, I've found this by accident while looking for something else :P

I added it a while ago but apparently forgot to add it to the JSON file. That has now been fixed, so @kenmoore can close this issue : )
