### ISSUE TITLE
Crash when pasting from a different Page

### ISSUE THREAD

**Issue by megrbui** [kenmoore/sketch-better-paste#7]
Sketch consistently crashes when I take the following steps:

(1) I copy something from Page 1
(2) I create Page 2
(3) I create 3 artboards in Page 2
(4) I zoom and scroll onto the Artboard I want to work with
(5) I press the command for Better Paste
(6) Sketch crashes

**Comment by kenmoore** [comment]
Hi mgnrsb, thanks for the report but I'm able to follow those steps without any crashes.  Please confirm that you're using the latest Better Paste (a consistent crashing bug was fixed a few months ago).  If you are on the latest plugin and can still repro, please provide more explicit steps starting from a clean launch of Sketch and starting with a blank document.  I'll do my best to track it down!
